tstl := "node_modules/typescript-to-lua/dist/tstl.js"

watch:
    bun "{{tstl}}" --watch

build:
    bun "{{tstl}}"

publish:
    cd .. && just publish 80gray-theme-adjuster 80gray-theme-adjuster/dist
