tstl := "node_modules/typescript-to-lua/dist/tstl.js"

build-all:
    #!bash

    for file in src/*.ts; do
        just build "$file"
    done


watch path:
    bun "{{tstl}}" --luaBundleEntry "{{path}}" --luaBundle "{{file_stem(path)}}.lua" --watch

build path:
    bun "{{tstl}}" --luaBundleEntry "{{path}}" --luaBundle "{{file_stem(path)}}.lua"
