tstl := "node_modules/typescript-to-lua/dist/tstl.js"

watch:
    bun "{{tstl}}" --watch

build:
    bun "{{tstl}}"

publish:
    cd .. && just publish select-track-by-routing select-track-by-routing/dist
